fix updateDatabase to dynamically get the correct user

diff --git a/devops-pipelines/templates/backend-deploy-stages.yml b/devops-pipelines/templates/backend-deploy-stages.yml
--- a/devops-pipelines/templates/backend-deploy-stages.yml
+++ b/devops-pipelines/templates/backend-deploy-stages.yml
@@ -164,10 +164,19 @@ stages:
                   scriptType: 'bash'
                   scriptLocation: 'inlineScript'
                   inlineScript: |
+                    # Get the clientId of the service principal used for the current deployment 
+                    appId=$(az account show --query user.name -o tsv)
+                    echo "Service Principal appId: $appId"
+
+                    # Get the service principal's app registration display name
+                    export SERVICE_PRINCIPAL=$(az ad app show --id "$appId" --query displayName -o tsv 2>/dev/null || true)
+
+                    echo "Service Principal display name: ${SERVICE_PRINCIPAL:-<not found>}"
+
                     bash $(scripts_directory)/updateDatabase.sh
                 env:
                   KEY_VAULT_NAME: $(keyVaultName)
-                  MIGRATION_SCRIPT_PATH: '$(Pipeline.Workspace)/build/database-scripts/migration-script.sql'
+                  MIGRATION_SCRIPT_PATH: '$(Pipeline.Workspace)/build/database-scripts/migration-script.sql' 
               
               - template: ./runner-cleanup-steps.yml
                 parameters:
