enforce formatting:
- Add pre-commit config
- Add pre-commit hook to run dornet format script
- Add pipeline task to verify dotnet formatting

diff --git a/devops-pipelines/templates/dotnet-build-steps.yml b/devops-pipelines/templates/dotnet-build-steps.yml
--- a/devops-pipelines/templates/dotnet-build-steps.yml
+++ b/devops-pipelines/templates/dotnet-build-steps.yml
@@ -8,6 +8,7 @@ parameters:
   nugetArtifactDownloadPath: "$(Build.SourcesDirectory)/localnuget"
   publishOutput: false
   runTests: false
+  checkFormatting: false
   testResultsDirectory: ""
 
 steps:
@@ -66,6 +67,30 @@ steps:
       ${{ if eq(parameters.useLocalNuGet, true) }}:
         nugetConfigPath: "$(Build.SourcesDirectory)/NuGet.Config"
         feedsToUse: "config"
+
+  - ${{ if eq(parameters.checkFormatting, true) }}:
+      - task: Bash@3
+        displayName: "Check Formatting"
+        inputs:
+          targetType: "inline"
+          script: |
+            set +e
+
+            echo "Checking for any dotnet formatting issues..."
+
+            output=$(
+              dotnet format ${{ parameters.projectPath }} --no-restore --verify-no-changes 2>&1)
+            exit_code=$?
+
+            echo "$output"
+
+            if [ $exit_code -ne 0 ]; then
+              echo "##vso[task.logissue type=error]dotnet format found formatting issues. Please run 'dotnet format ${{ parameters.projectPath }}' and commit the changes."
+              exit $exit_code
+            else
+              echo "No formatting issues were found."
+              exit $exit_code
+            fi
 
   # Build project
   - task: DotNetCoreCLI@2
