update backend pipelines to use self-hosted runners (#170)

diff --git a/devops-pipelines/backend/backend-build-and-publish.yml b/devops-pipelines/backend/backend-build-and-publish.yml
--- a/devops-pipelines/backend/backend-build-and-publish.yml
+++ b/devops-pipelines/backend/backend-build-and-publish.yml
@@ -13,14 +13,12 @@ variables:
   buildConfiguration: 'Release'
   dotNetVersion: '8.x'
   testResultsDirectory: '$(Agent.TempDirectory)/TestResults'
-  coverageReportsDirectory: '$(Agent.TempDirectory)/CoverageReports'
 
-pool:
-  vmImage: ubuntu-latest
+pool: 'LACC PreProd Pool'
 
 stages:
   - stage: Package_NuGet
-    displayName: 'LACC Backend - Produce Nuget Package'
+    displayName: 'Produce Nuget Package'
     jobs: 
     - job: Package_NuGet
       displayName: 'Pack and Publish NuGet Package'
@@ -55,7 +53,7 @@ stages:
             artifact: 'localnuget'
     
   - stage: Build_Main_API
-    displayName: 'LACC Backend - Build Main API'
+    displayName: 'Build Main API'
     dependsOn: Package_NuGet
     jobs:
       - job: Build_Main_API
@@ -72,7 +70,7 @@ stages:
               runTests: false
 
   - stage: Build_Filetransfer_API
-    displayName: 'LACC Backend - Build Main API'
+    displayName: 'Build Transfer API'
     dependsOn: Package_NuGet
     jobs:
       - job: Build_FileTransfer_API
@@ -89,13 +87,11 @@ stages:
               runTests: false
 
   - stage: Package_Database
-    displayName: 'LACC Backend - Build Database Migration Scripts'
+    displayName: 'Build Database Migration Scripts'
     dependsOn: Package_NuGet
     jobs:
       - job: Package_Database_Scripts
         displayName: 'Package Database Migration Scripts'
-        pool:
-          vmImage: ubuntu-latest
         steps:
           # Build Data project with dependencies
           - template: ../templates/dotnet-build-steps.yml
@@ -108,19 +104,22 @@ stages:
               publishOutput: false
               runTests: false
 
-          - task: DotNetCoreCLI@2
-            displayName: 'Install EF Core Tools'
-            inputs:
-              command: 'custom'
-              custom: 'tool'
-              arguments: 'install --global dotnet-ef'
-
-          - task: DotNetCoreCLI@2
+          - task: Bash@3
             displayName: 'Generate Migration Scripts'
             inputs:
-              command: 'custom'
-              custom: 'ef'
-              arguments: 'migrations script --idempotent --output $(Build.ArtifactStagingDirectory)/migration-script.sql --project backend/CPS.ComplexCases.Data/CPS.ComplexCases.Data.csproj --startup-project backend/CPS.ComplexCases.API/CPS.ComplexCases.API.csproj'
+              targetType: 'inline'
+              script: |
+                export PATH="$PATH:$HOME/.dotnet/tools"
+                
+                if ! dotnet ef --version &> /dev/null; then
+                  dotnet tool install --global dotnet-ef
+                fi
+
+                dotnet ef migrations script \
+                --idempotent \
+                --output $(Build.ArtifactStagingDirectory)/migration-script.sql \
+                --project backend/CPS.ComplexCases.Data/CPS.ComplexCases.Data.csproj \
+                --startup-project backend/CPS.ComplexCases.API/CPS.ComplexCases.API.csproj
 
           - task: CopyFiles@2
             displayName: 'Copy Migration Files'
@@ -128,6 +127,17 @@ stages:
               sourceFolder: 'backend/CPS.ComplexCases.Data/Migrations'
               contents: '**'
               targetFolder: '$(Build.ArtifactStagingDirectory)/migrations'
+
+          - script: |
+              echo "Checking if the zip package is installed..."
+              if ! zip --version &> /dev/null; then
+                echo "Zip command not found. Installing the zip package..."
+                sudo apt-get update
+                sudo apt-get install zip -y
+              else
+                echo "Zip is already installed."
+              fi
+            displayName: 'Ensure zip'
 
           - task: ArchiveFiles@2
             displayName: 'Archive Database Scripts'
