test migrations list

diff --git a/devops-pipelines/backend/backend-build-and-publish.yml b/devops-pipelines/backend/backend-build-and-publish.yml
--- a/devops-pipelines/backend/backend-build-and-publish.yml
+++ b/devops-pipelines/backend/backend-build-and-publish.yml
@@ -93,6 +93,8 @@ stages:
     jobs:
       - job: Package_Database_Scripts
         displayName: 'Package Database Migration Scripts'
+        variables: 
+        - group: lacc-backend-secrets-dev
         steps:
           # Build Data project with dependencies
           - template: ../templates/dotnet-build-steps.yml
@@ -124,39 +126,40 @@ stages:
 
                 migrations=$(dotnet ef migrations list \
                 --project backend/CPS.ComplexCases.Data/CPS.ComplexCases.Data.csproj \
-                --startup-project backend/CPS.ComplexCases.API/CPS.ComplexCases.API.csproj)
+                --startup-project backend/CPS.ComplexCases.API/CPS.ComplexCases.API.csproj \
+                --connection '$(CaseManagementDatastoreConnection)')
 
                 echo $migrations
 
-          - task: CopyFiles@2
-            displayName: 'Copy Migration Files'
-            inputs:
-              sourceFolder: 'backend/CPS.ComplexCases.Data/Migrations'
-              contents: '**'
-              targetFolder: '$(Build.ArtifactStagingDirectory)/migrations'
+          # - task: CopyFiles@2
+          #   displayName: 'Copy Migration Files'
+          #   inputs:
+          #     sourceFolder: 'backend/CPS.ComplexCases.Data/Migrations'
+          #     contents: '**'
+          #     targetFolder: '$(Build.ArtifactStagingDirectory)/migrations'
 
-          - script: |
-              echo "Checking if the zip package is installed..."
-              if ! zip --version &> /dev/null; then
-                echo "Zip command not found. Installing the zip package..."
-                sudo apt-get update
-                sudo apt-get install zip -y
-              else
-                echo "Zip is already installed."
-              fi
-            displayName: 'Ensure zip'
+          # - script: |
+          #     echo "Checking if the zip package is installed..."
+          #     if ! zip --version &> /dev/null; then
+          #       echo "Zip command not found. Installing the zip package..."
+          #       sudo apt-get update
+          #       sudo apt-get install zip -y
+          #     else
+          #       echo "Zip is already installed."
+          #     fi
+          #   displayName: 'Ensure zip'
 
-          - task: ArchiveFiles@2
-            displayName: 'Archive Database Scripts'
-            inputs:
-              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
-              includeRootFolder: false
-              archiveType: 'zip'
-              archiveFile: '$(Build.ArtifactStagingDirectory)/database-scripts.zip'
-              replaceExistingArchive: true
+          # - task: ArchiveFiles@2
+          #   displayName: 'Archive Database Scripts'
+          #   inputs:
+          #     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
+          #     includeRootFolder: false
+          #     archiveType: 'zip'
+          #     archiveFile: '$(Build.ArtifactStagingDirectory)/database-scripts.zip'
+          #     replaceExistingArchive: true
 
-          - task: PublishBuildArtifacts@1
-            displayName: 'Publish Database Scripts'
-            inputs:
-              pathtoPublish: '$(Build.ArtifactStagingDirectory)/database-scripts.zip'
-              artifactName: 'database-scripts-drop'
+          # - task: PublishBuildArtifacts@1
+          #   displayName: 'Publish Database Scripts'
+          #   inputs:
+          #     pathtoPublish: '$(Build.ArtifactStagingDirectory)/database-scripts.zip'
+          #     artifactName: 'database-scripts-drop'
